baseURL: "https://giurdeluca.github.io" 
title: Giulia Raffaella De Luca
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 40

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Talks
          url: talks/
          weight: 4
        - name: Blog
          url: blog/
          weight: 6

params:
    description: "This website hosts Giulia Raffaella De Luca's research papers, talks, curriculum vitae, and contact information."
    author: Giulia Raffaella De Luca
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: auto
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","blog","talks"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: false
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Giulia Raffaella De Luca, MS
          subtitle: "I am a PhD student at the University of Bologna, Italy. My research focuses on the use of AI in lung cancer screening. I graduated in biomedical engineering in 2023."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Blog
              url: blog/
            - name: Talks
              url: talks/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: shortcv-latex-apr2025-eng.pdf
        - name: Email
          url: mailto:giulia.deluca19@unibo.it
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=HmCVrxIAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/giurdeluca

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Giulia Raffaella De Luca"
      icon: bunny.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

titleCaseStyle: 'none'
enableGitInfo: true